# src/repositories/violation_repository.py
from abc import ABC, abstractmethod
from typing import List, Optional
from sqlalchemy.orm import Session
from src.models import ViolationReport
from src.repositories.base import BaseRepository

class IViolationRepository(ABC):
    @abstractmethod
    def get_list(
        self, 
        reporter_role: Optional[str] = None, 
        reporter_name: Optional[str] = None, 
        status_filter: Optional[str] = None
    ) -> List[ViolationReport]:
        pass

class ViolationRepository(BaseRepository[ViolationReport], IViolationRepository):
    def __init__(self, db: Session):
        super().__init__(ViolationReport, db)

    def get_list(
        self, 
        reporter_role: Optional[str] = None, 
        reporter_name: Optional[str] = None, 
        status_filter: Optional[str] = None
    ) -> List[ViolationReport]:
        query = self.db.query(ViolationReport)
        
        # Apply permissions / roles logic at repository level or service level
        if reporter_role == "citizen" and reporter_name:
            # Citizens see verified public reports OR their own reports (pending/verified/rejected)
            query = query.filter(
                (ViolationReport.status == "verified") |
                ((ViolationReport.reporter_role == "citizen") & (ViolationReport.reporter_name == reporter_name))
            )
        elif reporter_role == "ai_system":
            # AI system sees reports generated by AI system
            query = query.filter(ViolationReport.reporter_role == "ai_system")
            
        if status_filter:
            query = query.filter(ViolationReport.status == status_filter)
            
        # Newest first
        return query.order_by(ViolationReport.violation_time.desc()).all()
